joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 4.7124
    has_acceleration_limits: false
    max_acceleration: 0
  joint_2:
    has_velocity_limits: true
    max_velocity: 3.5343
    has_acceleration_limits: false
    max_acceleration: 0
  joint_3:
    has_velocity_limits: true
    max_velocity: 4.7124
    has_acceleration_limits: false
    max_acceleration: 0
  joint_4:
    has_velocity_limits: true
    max_velocity: 5.6549
    has_acceleration_limits: false
    max_acceleration: 0
  joint_5:
    has_velocity_limits: true
    max_velocity: 5.6549
    has_acceleration_limits: false
    max_acceleration: 0
  joint_6:
    has_position_limits: true
    min_position: -3.15
    max_position: 3.15
    has_velocity_limits: true
    max_velocity: 5.6549
    has_acceleration_limits: false
    max_acceleration: 0
    angle_wraparound: true